- name: users | radio | copy dotfiles
  tags: dotfiles,users,radio,tmux,users,vim,zsh
  copy:
    src: files/{{ item.src }}
    dest: /home/radio/{{ item.dest }}
    owner: radio
    group: radio
    mode: 0600
  with_items:
    - { src: 'bash_aliases', dest: '.bash_aliases' }
    - { src: 'zshrc', dest: '.zshrc' }
