- name: users | root | copy dotfiles
  copy:
    src: files/{{ item.src }}
    dest: /root/{{ item.dest}}
    owner: root
    group: root
    mode: 0600
  with_items:
      - { src: 'bash_aliases', dest: '.bash_aliases' }
      - { src: 'zshrc', dest: '.zshrc' }
  tags: dotfiles
