- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - apt-transport-https
      - colordiff
      - "{{ dns_utils_package}}"
      - htop
      - iotop
      - "{{ lm_sensors_package }}"
      - lsof
      - ncdu
      - neofetch
      - net-tools
      - "{{ nfs_client_package }}"
      - nmap
      - ranger
      - "{{ rename_package }}"
      - rsync
      - tmux
      - traceroute
      - neovim
      - zip
      - zsh

